export const SELECT_MESSAGES = 'SELECT_MESSAGES';
export const INVALID_MESSAGES = 'INVALID_MESSAGES';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
